# Generated by Django 3.1.4 on 2020-12-30 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dot',
            name='x',
            field=models.FloatField(),
        ),
    ]
