# Generated by Django 3.1.4 on 2020-12-30 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dots', '0003_dot_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dot',
            name='x',
            field=models.IntegerField(),
        ),
    ]
